language: php
php:
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: 7

script:
  - phpunit --configuration tests/phpunit.xml
  - ./bin/phpcs -p --standard=tests/phpcs/ruleset.xml lib/
  - ./bin/sabre-cs-fixer fix lib/ --dry-run --diff

before_script: composer install
