language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.5.9
  - 5.5.10
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: 5.5.10

matrix:
    allowed_failures:
        - php: hhvm

script:
  - phpunit --configuration tests/phpunit.xml
  - ./bin/vobject -h

before_script: composer install
