language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
    allowed_failures:
        - rvm: hhvm

script:
  - phpunit --configuration tests/phpunit.xml
  - ./bin/vobject -h

before_script: composer install
